galaxy_info:
  author: Vytenis
  description: "Installs NVIDIA drivers and configures the system for optimal GPU performance on MacPro51."
  license: MIT
  min_ansible_version: "2.9"
dependencies: []
