- name: Install Homebrew on macOS
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  args:
    creates: "/opt/homebrew/bin/brew"
  when: ansible_facts['os_family'] == 'Darwin'
  become: yes
