---
# Metadata for Open WebUI role

galaxy_info:
  author: your_name
  description: Install and configure Open WebUI on Manjaro Linux using Docker
  company: your_company
  license: MIT
  min_ansible_version: "2.9"

dependencies: []
