- name: Set NVIDIA environment variables for GBM backend
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    create: yes
    state: present
  loop:
    - "GBM_BACKEND=nvidia-drm"
    - "__GLX_VENDOR_LIBRARY_NAME=nvidia"
  notify: Reboot System
  become: yes
