- name: Ensure Docker is installed
  ansible.builtin.package:
    name: docker
    state: present
  become: yes

- name: Ensure Docker Compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present
  become: yes

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Create OpenProject Docker directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/Docker/openproject
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml template for OpenProject
  ansible.builtin.template:
    src: files/docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/Docker/openproject/docker-compose.yml
  become: yes

- name: Run Docker Compose for OpenProject
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: /home/{{ ansible_user }}/Docker/openproject
  become: yes
  notify: Restart OpenProject Container
