---
# Main tasks for setting up yay and installing AUR packages

- name: Update the package cache
  pacman:
    update_cache: yes
  become: yes

- name: Install yay using pacman
  pacman:
    name: yay
    state: present
    update_cache: yes
  become: yes

- name: Install AUR packages
  command: "yay -S --noconfirm {{ item }}"
  loop: "{{ yay_packages }}"