---
# Main tasks for setting up Ollama Docker with Nvidia GPU support

- name: Install dependencies
  pacman:
    name:
      - docker
      - nvidia-container-toolkit
    state: present
    update_cache: yes
  become: yes

- name: Ensure Docker is started and enabled
  systemd:
    name: docker
    enabled: true
    state: started
  become: yes

- name: Configure Nvidia container toolkit
  shell: |
    sudo systemctl restart docker
  become: yes

- name: Pull the Ollama Docker image
  docker_image:
    name: ollama/ollama
    source: pull
  become: yes

- name: Run Ollama Docker container with Nvidia GPU support
  docker_container:
    name: ollama
    image: ollama/ollama
    state: started
    restart_policy: unless-stopped
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    device_requests:
      - capabilities:
          - gpu
  become: yes
  notify: Restart Docker

