galaxy_info:
  author: Vytenis
  description: "Configures GRUB to remove the splash screen, show text output during boot, and set GRUB timeout on Manjaro Linux."
  license: MIT
  min_ansible_version: "2.9"
dependencies: []
